/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/darth-vader.glb 
*/

import { OrbitControls, useGLTF } from '@react-three/drei'

export const DarthVaderSaber = () => {
  const { nodes, materials } = useGLTF('/models/darth-vader.glb')
  const initialPosition = [0, -120, 0]

  return (
  <>
    <OrbitControls autoRotate />
    <group dispose={null} position={initialPosition}>
      <mesh geometry={nodes.emitter.geometry} material={materials['Black plastic']} position={[-23.963, -1.158, -30.774]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.emitter_shroud.geometry} material={materials['Black plastic']} position={[-23.963, -1.158, -30.774]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.d_ring.geometry} material={materials.Steel} position={[13.618, 254.938, -21.699]} rotation={[3.109, 0, Math.PI / 2]} />
      <mesh geometry={nodes.bolt1.geometry} material={materials['Steel darkness']} position={[-5.33, 248.978, -27.133]} rotation={[-3.14, 0, 0]} />
      <mesh geometry={nodes.bolt2.geometry} material={materials['Steel darkness']} position={[-4.315, 221.712, -27.171]} rotation={[-3.14, 0, 0]} />
      <mesh geometry={nodes.upper_chamber.geometry} material={materials.Steel} position={[-24.557, 163.813, 8.04]} rotation={[1.572, 0, -1.053]} />
      <mesh geometry={nodes.midsection.geometry} material={materials['Black plastic']} position={[-23.963, 0.042, -30.772]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.power_block.geometry} material={materials['Black plastic']} position={[-23.963, -1.158, -30.774]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.power_casing.geometry} material={materials['Black plastic']} position={[-6.56, 118.416, 32.798]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.power_switch.geometry} material={materials.Steel} position={[-24.305, -0.818, -31.378]} rotation={[1.572, 0, 0]} />
      <mesh geometry={nodes.power_regulator.geometry} material={materials.Steel} position={[14.094, 144.523, 27.414]} rotation={[-3.14, 0, Math.PI / 2]} />
      <mesh geometry={nodes.pommel.geometry} material={materials.Steel} position={[15.574, 0.028, -36.012]} rotation={[1.572, 0, Math.PI / 3]} />
      <mesh geometry={nodes.pommel_block1.geometry} material={materials['Black plastic']} position={[-39.219, -0.553, 9.678]} rotation={[1.572, 0, -1.077]} />
      <mesh geometry={nodes.pommel_block2.geometry} material={materials['Black plastic']} position={[-16.058, -0.589, 35.683]} rotation={[1.572, 0, -2.048]} />
      <mesh geometry={nodes.pommel_block3.geometry} material={materials['Black plastic']} position={[24.347, -0.585, 32.825]} rotation={[1.572, 0, -3.129]} />
      <mesh geometry={nodes.pommel_block4.geometry} material={materials['Black plastic']} position={[-22.84, -0.497, -30.344]} rotation={[1.572, 0, 0.03]} />
      <mesh geometry={nodes.pommel_block5.geometry} material={materials['Black plastic']} position={[13.272, -0.49, -35.534]} rotation={[1.572, 0, 0.995]} />
      <mesh geometry={nodes.pommel_block6.geometry} material={materials['Black plastic']} position={[38.429, -0.536, -2.756]} rotation={[1.572, 0, 2.129]} />
    </group>
  </>
  )
}

useGLTF.preload('/models/darth-vader.glb')
